// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_BinaryTreeGUI_0_H
#define WINRT_BinaryTreeGUI_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::BinaryTreeGUI
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::BinaryTreeGUI::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::BinaryTreeGUI::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::BinaryTreeGUI::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::BinaryTreeGUI::MainWindow> = L"BinaryTreeGUI.MainWindow";
    template <> inline constexpr auto& name_v<winrt::BinaryTreeGUI::XamlMetaDataProvider> = L"BinaryTreeGUI.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::BinaryTreeGUI::IMainWindow> = L"BinaryTreeGUI.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::BinaryTreeGUI::IMainWindow>{ 0xA2F03258,0x02A8,0x5063,{ 0x8E,0xF2,0x97,0x29,0xB0,0x5E,0x33,0x06 } }; // A2F03258-02A8-5063-8EF2-9729B05E3306
    template <> struct default_interface<winrt::BinaryTreeGUI::MainWindow>{ using type = winrt::BinaryTreeGUI::IMainWindow; };
    template <> struct default_interface<winrt::BinaryTreeGUI::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::BinaryTreeGUI::IMainWindow>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_BinaryTreeGUI_IMainWindow
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::BinaryTreeGUI::IMainWindow>
    {
        template <typename D> using type = consume_BinaryTreeGUI_IMainWindow<D>;
    };
}
#endif
