// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

void* winrt_make_BinaryTreeGUI_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::BinaryTreeGUI::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::BinaryTreeGUI
{
    MainWindow::MainWindow() :
        MainWindow(make<BinaryTreeGUI::implementation::MainWindow>())
    {
    }
}
