// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

void* winrt_make_BinaryTreeGUI_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::BinaryTreeGUI::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::BinaryTreeGUI
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<BinaryTreeGUI::implementation::XamlMetaDataProvider>())
    {
    }
}
